'on':
  github:
    branches:
      only: main
defaults:
  # Default instance type for all jobs
  resources:
    instance-type: P6000
  # Default environment variables for all jobs
  env:
    # Provide secrets
    UPLOAD_URL_BASE: secret:UPLOAD_URL_BASE
    UPLOAD_KEY: secret:UPLOAD_KEY
    DATA_SET: tinyshakespeare
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  TrainModel:
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      model:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        set -e

        curl -s "$UPLOAD_URL_BASE"

        mkdir -p /outputs/model
        cd /inputs/repo
        python "${DATA_SET}.py" download
        python "${DATA_SET}.py" pretokenize
        python train.py --dataset=${DATA_SET} --max_iters=10000 --dtype=float16 --compile=False --always_save_checkpoint=True

        mv out/ckpt.pt /outputs/model/ckpt.pt
        mv out/model.bin "/outputs/model/${DATA_SET}-15M.bin"
        mv "data/${DATA_SET}.bin" "/outputs/model/${DATA_SET}-tokens.bin"
      image: paperspace/gradient-base:pt112-tf29-jax0314-py39-20220803

