'on':
  github:
    branches:
      only: main
defaults:
  # Default instance type for all jobs
  resources:
    instance-type: P6000
  # Default environment variables for all jobs
  env:
    # Provide secrets
    UPLOAD_URL_BASE: secret:UPLOAD_URL_BASE
    UPLOAD_KEY: secret:UPLOAD_KEY
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  TrainModel:
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      model:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        set -e
        mkdir -p /outputs/model
        cd /inputs/repo
        python tinyshakespeare.py download
        python tinyshakespeare.py pretokenize
        python train.py --dataset=tinyshakespeare --max_iters=100 --eval_iters=10 --eval_interval=10 --warmup_iters=10 --dtype=float16 --compile=False --always_save_checkpoint=True

        mv out/ckpt.pt /outputs/model/ckpt.pt
        mv out/model.bin /outputs/model/tinyshakespeare-15M.bin
        mv data/tinyshakespeare.bin /outputs/model/tinyshakespeare-tokens.bin
      image: paperspace/gradient-base:pt112-tf29-jax0314-py39-20220803

